version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - frontend
      - backend
    ports:
      - "30080:80"
      - "38080:8080"
      - "30443:443"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: tid-html
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=tiduser
      - MYSQL_PASSWORD=tidpass 
      - MYSQL_DATABASE=tid_db
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    container_name: tid-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    links: 
        - mysql:mysql
    # depends_on:
    #   - mysql
    networks:
      - backend
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=tid-mysql
      - MYSQL_USER=tiduser
      - MYSQL_PASSWORD=tidpass
      -  MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - /sessions
    container_name: tid-phpmyadmin
networks:
  frontend:
  backend:
